server.port=8080
eureka.client.service-url.defaultZone=http://campushub-registry:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Gateway,Gateway

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://campushub-user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/campushub-user-service/**

# Actuator settings
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true
