server.port=808
spring.application.name=campushub-scheduling

eureka.client.serviceUrl.defaultZone=http://campushub-registry:8761/eureka/
eureka.instance.preferIpAddress=true

scheduling.timezone=Africa/yaounde
scheduling.default-duration-minutes=90
scheduling.conflict-detection=true
scheduling.max-events-per-day=20

logging.level.root=INFO
logging.level.campushub-scheduling=DEBUG
