server.port=8080
eureka.client.service-url.defaultZone=http://campushub-registry:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.discovery.locator.enabled=false
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.gateway.enabled=true
management.server.port=8081

spring.cloud.gateway.routes[0].id=test-route
spring.cloud.gateway.routes[0].uri=http://example.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/test/**