spring.application.name=campushub-user-service

# Port sur lequel il écoute
server.port=8081

# ===============================
# Connexion au Config Server
# ===============================
spring.config.import=optional:configserver:http://localhost:8888

# ===============================
# Eureka (Service Discovery)
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Base de données MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/campushub_user_db?createDatabaseIfNotExist=true
spring.datasource.username=usercampushub
spring.datasource.password=YES


# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



