server.port=8082

eureka.client.service-url.defaultZone=http://campushub-registry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.datasource.url=jdbc:mysql://campushub-salle-db:3306/campushub_salle_db?createDatabaseIfNotExist=true&useSSL=false&serverTimeZone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.devtools.jmx.enabled=false

# Secret JWT harmonisé avec l'ensemble du projet pour la communication inter-services
jwt.secret=c3b3f4d4a5e5b6c6d7e7f8a8b9c9d0e0f1a1b2c2d3e3f4a4b5c5d6e6f7a7b8c8
