spring.application.name=gateway-service

# Port exposé par le Gateway (ceci peut rester dans application.properties du service)
server.port=8081

# Activer la découverte de services
spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Activer la découverte automatique des routes
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Exemple de route vers salle-service
spring.cloud.gateway.routes[0].id=salle-service
spring.cloud.gateway.routes[0].uri=lb://salle-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/salle/**
spring.cloud.gateway.routes[0].filters[0]=AddRequestHeader=X-Gateway,Gateway
